hamlinux: aprs: update 'updateDXLaprs' script
Signed-off-by: Hannes Schmelzer <oe5hpm@oevsv.at>

diff --git a/board/hpm/hamlinux-arm7/rootfs-additions/root/utils/updateDXLaprs b/board/hpm/hamlinux-arm7/rootfs-additions/root/utils/updateDXLaprs
--- a/board/hpm/hamlinux-arm7/rootfs-additions/root/utils/updateDXLaprs
+++ b/board/hpm/hamlinux-arm7/rootfs-additions/root/utils/updateDXLaprs
@@ -1,57 +1,82 @@
 #!/bin/sh
-USER=`whoami`
-if [ "$USER" != "root" ]; then
-    echo "you must do this as root!"
-    exit 1
+# this script unpacks and installs remote or local installation archive images created
+# by the packCurrent.sh script.
+
+if [ -z $1 ]; then
+	echo "updateDXLaprs: missing architecture or local image file"
+	echo "Usage: updateDXLaprs ARCH | file"
+	echo "    Where ARCH may be: armv6, armv6tce, armv7hf, x86_32, x86_64, ..."
+	echo ""
+	echo "    If a local file is specified instead of one of the architectures above,"
+	echo "    then this file will be used for performing the installation. The local"
+	echo "    file must be a file that was created by the packCurrent.sh script."
+	exit 1
 fi
 
-DSTMAP=/home/dxlAPRS/aprsmap
-DSTAPRS=/home/dxlAPRS/aprs
 SOURCE=http://dxlaprs.hamspirit.at
-FILE=dxlAPRS_armv7hf-current
+FILE=dxlAPRS_$1-current
 
+DST=$HOME/dxlAPRS
+DSTMAP=$DST/aprsmap
+DSTAPRS=$DST/aprs
 
+# set up the destination directory structure
 [ -d $DSTMAP ] || mkdir -p $DSTMAP
 [ -d $DSTMAP/osm ] || mkdir -p $DSTMAP/osm
+[ -d $DSTMAP/logs ] || mkdir -p $DSTMAP/logs
 [ -d $DSTAPRS ] || mkdir -p $DSTAPRS
 
-cd /tmp
-[ -d dxlAPRS-update ] || mkdir dxlAPRS-update
-cd dxlAPRS-update
-[ -r $FILE.tgz ] && rm $FILE.tgz
-wget $SOURCE/$FILE.tgz
+# retrieve the image
+TMPDIR=$(mktemp -d)
+if [ $? -ne 0 ]; then
+	echo "Unable to create temporary directory."
+	exit 1
+fi
 
-if [ $? -eq 0 ] && [ -r $FILE.tgz ]; then
+# if a file exists simply assume it's a local packCurrent image else try to download
+if [ -f $1 ]; then
+	FILE=$(basename $1 .tgz)
+	cp -r $1 $TMPDIR
+	cd $TMPDIR
+else
+	cd $TMPDIR
+	wget $SOURCE/$FILE.tgz
+	if [ $? -ne 0 ]; then
+		echo "Unable to download image:" $SOURCE/$FILE.tgz
+		rm -r $TMPDIR
+		exit 1
+	fi
+fi
+
+# if image file exists then unpack and move files to their destinations
+if [ -r $FILE.tgz ]; then
 	gunzip $FILE.tgz
 	tar -xf $FILE.tar
 	rm $FILE.tar
-	echo "stopping all aprs-executeables ..."
-	killall afskmodem 2>/dev/null
-	killall gps2aprs 2>/dev/null
-	killall gps2digipos 2>/dev/null
-	killall sondemod 2>/dev/null
-	killall sondeudp 2>/dev/null
-	killall udpflex 2>/dev/null
-	killall udphub 2>/dev/null
-	killall udprfnet 2>/dev/null
-	killall udpgate4 2>/dev/null
-	killall udpbox 2>/dev/null
-	echo "installing aprsmap-components ..."
+	echo "Installation directory:" $DST
+	echo "Installing aprsmap-components..."
+	mv -f aprsmap_common/poi.txt $DSTMAP/osm/
 	mv -f aprsmap_common/* $DSTMAP/
-	mv -f aprsmap $DSTMAP/
 	rm -r aprsmap_common
-	echo "installing aprs-components ..."
-	mv -f dxlAPRS_common/* $DSTAPRS/
+	mv -f aprsmap* $DSTMAP/
+	echo "Installing aprs-components..."
+	cp -r dxlAPRS_common/* $DSTAPRS/
 	rm -r dxlAPRS_common
+	cp -r scripts $DSTAPRS/
+	rm -r scripts
 	mv -f * $DSTAPRS/
-	chown -R aprs:staff $DSTAPRS
-	chown -R aprs:staff $DSTMAP
-	chown root:staff $DSTAPRS/afskmodem
-	olddir=`pwd`
+
+# fixup file permissions and owners
 	cd $DSTAPRS
-	for f in $(\ls); do 
-		test -x $f && chmod 0755 $f
+	for f in $(ls); do
+		test -x $f && sudo chmod 0755 $f
 	done
-	chmod +s afskmodem
-	cd $olddir
+	sudo chown root afskmodem
+	sudo chmod +s afskmodem
+	rm -r $TMPDIR
+else
+# either cp or wget failed above somehow to get an image into TMPDIR
+	echo "Unable to locate temporary copy of image:" $FILE.tgz
+	rm -r $TMPDIR
+	exit 1
 fi
